com:
  giftedconcepts:
    validate:
      annotation:
        unprintableRegex: "\\P{Print}"
        allowedLegalValidationCharacters:
          - "149"
          - "8226"
          - "13"
          - "10"
          - "167"
          - "182"
#       BULLET BULLET_2 CR LF SECTION PARAGRAPH
